In [1]:
#importing essential libraries
import numpy as np
import pandas as pd


In [2]:
#Read the dataset
data = pd.read_csv('Dataset.txt')
print(data)

       Matrix   Alien   Star_wars   Csablanca   Titanic
Joe         1       1           1           0         0
jim         3       3           3           0         0
john        4       4           4           0         0
jack        5       5           5           0         0
jill        0       0           0           4         4
jenny       0       0           0           5         5
jane        0       0           0           2         2


In [3]:
users = list(data.index)
print(users)
M = [list(data.iloc[i]) for i in range(len(users))]
M = np.matrix(M,dtype=int)
print(M)

['Joe', 'jim', 'john', 'jack', 'jill', 'jenny', 'jane']
[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 0 0 4 4]
 [0 0 0 5 5]
 [0 0 0 2 2]]


In [4]:
def Recomender_SVD(M,dimension):
    #To calculate the orthonormal vector U
    vsu = np.dot(M,M.T)
    #Get eigen values and vectors
    eigen_value,eigen_vectors = np.linalg.eig(vsu)
    #It sorts the eigen_values in ascending values
    sort_indices = eigen_value.argsort()[::-1]
    eigen_value = eigen_value[sort_indices]
    #Sort and reduce U to nXdim
    U=eigen_vectors[:,sort_indices]
    U=U[:,0:dimension]
    U=np.real(U)
    
    #To calculate sigma(consists of eigen values)
    sigma=np.sqrt(abs(eigen_value))
    
   #Energy retained
    energy_density=np.sum(np.square(sigma))
    sigma=sigma[0:dimension]
    energy_num=np.sum(np.square(sigma))
    sigma=np.around(sigma,decimals=2)
    
    #Here we are checking whether the dimension chosen is optimal or >90% by dividing energy_num with energy_density
    print("Energy= ",energy_num/energy_density) 
    
    #Here we are calculating the orthonormal vector V 
    vsu = np.dot(M.T,M)
    eigen_value,eigen_vector=np.linalg.eig(vsu)
    sort_indices=eigen_value.argsort()[::-1]
    V=eigen_vector[:,sort_indices]
    V=V[:,0:dimension]
    V=np.real(V)
    
    return U,sigma,V
    

In [5]:
U,sigma,V=Recomender_SVD(M,2)

print("\nU", U)
print("\n sigma ", sigma)
print("\n V.Trans ", V.T)


Energy=  1.0

U [[-0.14002801  0.        ]
 [-0.42008403  0.        ]
 [-0.56011203  0.        ]
 [-0.70014004  0.        ]
 [ 0.          0.59628479]
 [ 0.          0.74535599]
 [ 0.          0.2981424 ]]

 sigma  [12.37  9.49]

 V.Trans  [[0.57735027 0.57735027 0.57735027 0.         0.        ]
 [0.         0.         0.         0.70710678 0.70710678]]


In [6]:
sigma = np.diag(sigma) #Converting into diagonal matrix where the diagonal elements are eigen values
SVD_M = abs(np.dot(np.dot(U,sigma),V.T))
print(SVD_M)
print(M)

[[1.00005523 1.00005523 1.00005523 0.         0.        ]
 [3.00016568 3.00016568 3.00016568 0.         0.        ]
 [4.00022091 4.00022091 4.00022091 0.         0.        ]
 [5.00027614 5.00027614 5.00027614 0.         0.        ]
 [0.         0.         0.         4.00133533 4.00133533]
 [0.         0.         0.         5.00166917 5.00166917]
 [0.         0.         0.         2.00066767 2.00066767]]
[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 0 0 4 4]
 [0 0 0 5 5]
 [0 0 0 2 2]]


In [7]:
#Queries Using the Singular-Value Decomposition
def Query(Q,V):
    USV = np.dot(Q,V)
    print("V  :",V)
    print(abs(USV))
    queried=np.dot(USV,V.T)
    print('\n',abs(queried))
    return

In [8]:
Q = [0,3,4,0,0] #User rating of the person who watches action-scifi movies
Query(Q,V)

V  : [[0.57735027 0.        ]
 [0.57735027 0.        ]
 [0.57735027 0.        ]
 [0.         0.70710678]
 [0.         0.70710678]]
[[4.04145188 0.        ]]

 [[2.33333333 2.33333333 2.33333333 0.         0.        ]]


In [11]:
Q = [0,0,0,3,2] #User rating of the person who watches romantic movies
Query(Q,V)

V  : [[0.57735027 0.        ]
 [0.57735027 0.        ]
 [0.57735027 0.        ]
 [0.         0.70710678]
 [0.         0.70710678]]
[[0.         3.53553391]]

 [[0.  0.  0.  2.5 2.5]]
